version: "3"
volumes:
  mariadb:
    driver: local
    driver_opts:
      o: bind
      type: 'none'
      device: /Users/souchen/data/db
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: /Users/souchen/data/wp
networks:
  inception:
    driver: bridge
  
services:
  mariadb:
    container_name: mariadb
    image: mariadb:inception
    ports:
      - 3306:3306
    build: ./requirements/mariadb
    env_file: 
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped 
    networks:
      - inception

  wordpress:
    container_name: wordpress
    image: wordpress:inception
    env_file: 
      - .env
    ports:
      - 9000:9000
    volumes:
      - wordpress:/var/www/html
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    restart: on-failure
    networks:
      - inception

  nginx:
    container_name: nginx
    image: nginx:inception
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    build: ./requirements/nginx
    env_file: 
      - .env
    depends_on:
      - wordpress
    restart: on-failure
    networks:
      - inception 
  

    













