version: "3"  
services:
  mariadb:
    container_name: mariadb
    image: mariadb:inception
    ports:
      - 3306:3306
    build: ./requirements/mariadb
    env_file: 
      - .env
    volumes:
      - mariadb_v:/var/lib/mysql
    restart: unless-stopped 
    networks:
      - inception_net

  wordpress:
    container_name: wordpress
    image: wordpress:inception
    env_file: 
      - .env
    ports:
      - 9000:9000
    volumes:
      - wordpress_v:/var/www/html
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    restart: on-failure
    networks:
      - inception_net

  nginx:
    container_name: nginx
    image: nginx:inception
    ports:
      - 443:443
    volumes:
      - wordpress_v:/var/www/html
    build: ./requirements/nginx
    env_file: 
      - .env
    depends_on:
      - wordpress
    restart: on-failure
    networks:
      - inception_net 
  
volumes:
  mariadb_v:
    driver: local
    driver_opts:
      o: bind
      type: 'none'
      device: /home/souchen/data/db
  wordpress_v:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: /home/souchen/data/wp
networks:
  inception_net:
    driver: bridge
    













