version: "3"
volumes:
  mariadb:
    driver: local
    driver_opts:
      o: bind
      type: 'none'
      device: /goinfre/souchen/inception/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: /goinfre/souchen/inception/wordpress
services:
  mariadb:
    image: mariadb
    ports:
      - 3360:3360
    build: ./requirements/mariadb
    env_file: 
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped 

  wordpress:
    image: wordpress
    env_file: 
      - .env
    ports:
      - 9000:9000
    volumes:
      - wordpress:/var/www/wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    restart: on-failure

  nginx:
    image: nginx
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - 443:443
    depends_on:
      - wordpress
    build: ./requirements/nginx
    env_file: 
      - .env
    restart: on-failure   
  
  
    













