version: "3"
volumes:
  mariadb:
    driver: local
    driver_opts:
    o: bind
    type: 'none'
    device: /home/souchen/data/mariadb
  wordpress:
    driver: local
    driver_opts:
    type: 'none'
    o: bind
    device: /home/souchen/data/wordpress
networks:
  appInception:
    driver: bridge
services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      SQL_DATABASE: wordpress
      SQL_USER: souchen
      SQL_PASSWORD: "1234"
    volumes:
      - mysql_vol:/var/lib/mysql
    restart: unless-stopped
    networks:
      - appInception

  wordpress:
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: souchen
      WORDPRESS_DB_PASSWORD: "123456"
      WORDPRESS_DB_NAME: wp
    ports:
      - 8000:80
    volumes:
      ["./:/var/www/html"]
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    restart: on-failure
    networks:
      - appInception

volumes:
  mysql_vol: {}