version: "3"
# volumes:
#   mariadb:
#     driver: local
#     driver_opts:
#       o: bind
#       type: 'none'
#       device: /Users/souchen/data/mariadb
#   wordpress:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: bind
#       device: /Users/souchen/data/mariadb

services:
  mariadb:
    container_name: mariadb
    image: mariadb:inception
    ports:
      - 3360:3360
    build: ./requirements/mariadb
    env_file: 
      - .env
    volumes:
      - mysql_vol:/var/lib/mysql
    restart: unless-stopped 

  wordpress:
    container_name: wordpress
    image: wordpress:inception
    env_file: 
      - .env
    ports:
      - 9000:9000
    volumes: ["./:/var/www/html"]
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    restart: on-failure

  nginx:
    container_name: nginx
    image: nginx:inception
    volumes: ["./:/var/www/html"]
    ports:
      - 443:443
    depends_on:
      - wordpress
    build: ./requirements/nginx
    env_file: 
      - .env
    restart: on-failure 

volumes:
    mysql_vol: {}
  
  
    













