FROM debian:buster
RUN apt update
RUN apt-get install -y php7.3 php-fpm php-mysqli mariadb-client sendmail wget
COPY ./conf/auto_config.sh /var/www/
RUN chmod +x /var/www/auto_config.sh
ENTRYPOINT [ "/var/www/auto_config.sh" ]
CMD ["/usr/sbin/php-fpm7.3", "--nodaemonize"]

