FROM debian:buster
RUN apt update
RUN apt-get -y install wget
RUN apt-get install -y php7.3 php-fpm php-mysql mariadb-client
RUN sed -i "s/listen = \/run\/php\/php7.3-fpm.sock/listen = 9000/" "/etc/php/7.3/fpm/pool.d/www.conf"
RUN wget https://wordpress.org/latest.tar.gz -P /var/www
RUN cd /var/www && tar -xzvf latest.tar.gz && rm latest.tar.gz
# COPY ./conf/auto_config.sh /var/www/
RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar
RUN mv wp-cli.phar /usr/local/bin/wp
RUN touch /var/www/wordpress/wp-config.php;
# RUN sed -i "s/votre_nom_de_bdd/${SQL_DATABASE}/g" "/var/www/wordpress/wp-config-sample.php"
# RUN sed -i "s/votre_utilisateur_de_bdd/${SQL_USER}/g" "/var/www/wordpress/wp-config-sample.php"
# RUN sed -i "s/votre_mdp_de_bdd/${SQL_PASSWORD}/g" "/var/www/wordpress/wp-config-sample.php"
# RUN sed -i "s/localhost/${db_host}/g" "/var/www/wordpress/wp-config-sample.php"
# RUN cp /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php:q!

# RUN chmod +x /var/www/auto_config.sh
# ENTRYPOINT [ "/var/www/auto_config.sh" ]
